language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - mkdir -p tests/_coverage
script:
  - pipenv run pytest tests/ --cov watson --cov-report term-missing
after_success:
  - pipenv run coveralls --verbose
notifications:
  slack:
    secure: T/JltnYcwN8CJaqkzMOZmMPPbwOEeW2MkDn/aEVZ9uz9pQBalUIxuzcbhFSUvtQWJhKzHllFiC2caLQM5khal7zebRkQtcifDoKVbrQpJrAANc74KEQpuFN5ALYI1ts7Ec7G7AfkNAywYKzP0rZhgFvmhbIor2jErO6oyCULLeM=
